---
title: "Schedule of workshop events"
site: distill::distill_website
listing: posts
---

# About

The Computational Social Science (CSS) Technical Skills Workshop trains participants in technical skills and methods which are relevant to computationally-driven research, but are not typically taught in for-credit courses. It provides an explicit introduction to core software environments and interfaces which impose a barrier to access for individuals lacking prior exposure to programming, and facilitates a community of computational researchers across the [Division of the Social Sciences](https://socialsciences.uchicago.edu/). Individual workshops are designed for a range of technical backgrounds, including purely introductory methods as well as intermediate or advanced training in specific software or computational techniques. Workshops are designed for hands-on learning, and will include substantial live-coding exercises.

The workshop is organized by the [Masters Program in Computational Social Science](https://macss.uchicago.edu/) at the [University of Chicago](https://www.uchicago.edu) and meets biweekly on Tuesdays from 3:30-5:20pm in room 295 at [1155 E 60th St](https://goo.gl/maps/uy2gHVc3bkrS5W4H8). All members of the University community are invited to participate. Due to the ongoing public health crisis, all participants will be required to register in advance for each workshop.
