---
title: "Introduction to Git and GitHub"
description: |
  Version control software such as Git is essential for collaboration and version
  tracking on data science projects, however the learning curve for Git is quite steep. In this
  workshop we will practice common workflows using Git and GitHub.
author:
  - name: Benjamin Soltoff
    url: https://www.bensoltoff.com
    affiliation: University of Chicago
    affiliation_url: https://macss.uchicago.edu
date: 2022-03-08
creative_commons: CC BY-NC
output:
  distill::distill_article:
    keep_md: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Overview

[Git](https://git-scm.com/) is a common tool in software development for version control, while [GitHub](https://github.com/) is a cloud-based service that works in conjunction with the Git software to facilitate version control and collaboration. These tools can be used to improve data science workflows and computationally-enhanced research projects. However the learning curve for Git is quite steep, and often individuals are left to learn Git on their own with little explicit instruction. In this workshop we will introduce Git/GitHub and practice common workflows.

## Objectives

- Identify the value of version control software for data science projects
- Create repositories
- Make commits and synchronize repositories
- Implement collaborative workflows using branches and forks
- Generate pull requests

## Audience

This workshop is designed for individuals with introductory-to-intermediate experience programming in a language such as Python or R.

## Location

Room 295 in [1155 E 60th St](https://goo.gl/maps/7n7wDsd9mjnfRBtR8).

## Prework

- Register for this workshop. Due to the current public health crisis, all participants must register in advance using [this form.](https://forms.gle/z5A4r9QmF9DYYcon7)
- Please sign up for a free [RStudio Cloud account](https://rstudio.cloud).
- Once you have created your RStudio Cloud account, [join the workshop organization.](https://rstudio.cloud/spaces/177434/join?access_code=cGV7c0V8%2Bpr0kFC5NkOX%2FgxNNhIm3PchWX1CjdBf)

## Links

